# Generated by Django 5.0.1 on 2024-01-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_type', models.CharField(choices=[('debit_card', 'debit_card'), ('credit_card', 'credit_card'), ('prepaid_card', 'prepaid_card'), ('overdraft_card', 'overdraft_card'), ('current_account', 'current_account'), ('credit_account', 'credit_account'), ('currency_account', 'currency_account'), ('deposit_account', 'deposit_account')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('payment_limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('paid', 'paid'), ('canceled', 'canceled')], max_length=50)),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.requisites')),
            ],
        ),
    ]
